# Generated by Django 5.2 on 2025-05-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
    ]
