# Generated by Django 5.2 on 2025-05-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_tarefa_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
    ]
