# Generated by Django 5.2 on 2025-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_tarefa_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
